Repository Team-Safezone/Safezone-Server, pull requests merged in 2024-09, with the labels that each got.

#39 🎉 Feat: 시즌 팀 정보 Entity, 모든 시즌 팀 이름 전체 조회 GET API 추가, enum 대신 DB 조회하도록 전체 코드 수정
  src/main/java/KickIt/server/domain/fixture/controller/FixtureController.java
  src/main/java/KickIt/server/domain/fixture/dto/FixtureDto.java
  src/main/java/KickIt/server/domain/fixture/entity/Fixture.java
  src/main/java/KickIt/server/domain/fixture/entity/FixtureRepository.java
  src/main/java/KickIt/server/domain/fixture/service/FixtureService.java
  src/main/java/KickIt/server/domain/lineup/entity/MatchLineup.java
  src/main/java/KickIt/server/domain/lineup/entity/TeamLineup.java
  src/main/java/KickIt/server/domain/teams/controller/EplTeamController.java
  src/main/java/KickIt/server/domain/teams/dto/EplTeamDto.java
  src/main/java/KickIt/server/domain/teams/entity/EplTeam.java
  src/main/java/KickIt/server/domain/teams/entity/EplTeamRepository.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/domain/teams/entity/Squad.java
  src/main/java/KickIt/server/domain/teams/service/EplTeamService.java
  src/main/java/KickIt/server/domain/teams/service/TeamNameConvertService.java
  src/main/java/KickIt/server/global/common/crawler/FixtureCrawler.java
  src/main/java/KickIt/server/global/common/crawler/LineupCrawler.java
  src/main/java/KickIt/server/global/common/crawler/SquadCrawler.java
  src/main/java/KickIt/server/global/common/crawler/test.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore, ♻️ Refactor

#38 Sf 71/feat/#34 code refactoring
  src/main/java/KickIt/server/ServerApplication.java
  src/main/java/KickIt/server/domain/fixture/dto/FixtureDto.java
  src/main/java/KickIt/server/domain/fixture/entity/Fixture.java
  src/main/java/KickIt/server/domain/lineup/entity/MatchLineup.java
  src/main/java/KickIt/server/domain/realtime/RealTime.java
  src/main/java/KickIt/server/domain/realtime/controller/RealTimeController.java
  src/main/java/KickIt/server/domain/realtime/dto/RealTimeDto.java
  src/main/java/KickIt/server/domain/realtime/dto/RealTimeRepository.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTime.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeService.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeStart.java
  src/main/java/KickIt/server/domain/teams/controller/TeaminfoController.java
  src/main/java/KickIt/server/domain/teams/dto/TeaminfoDto.java
  src/main/java/KickIt/server/domain/teams/entity/Squad.java
  src/main/java/KickIt/server/domain/teams/entity/Teaminfo.java
  src/main/java/KickIt/server/domain/teams/entity/TeaminfoRepository.java
  src/main/java/KickIt/server/domain/teams/service/TeaminfoService.java
  src/main/java/KickIt/server/global/common/crawler/RTCrawler.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeCrawler.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeDataParser.java
  src/main/java/KickIt/server/global/common/crawler/TeaminfoCrawler.java
  src/main/java/KickIt/server/global/util/Scheduler.java
  src/main/resources/application.properties
  src/test/java/KickIt/Server/StatusTest.java
Labels: 🎉 Feat, 🌷 윤수, ♻️ Refactor, :page_facing_up: Data Crawling

#45 🎉 Feat: 시즌별 각 팀 선수 명단, 선수 정보 entity, post api 개발
  src/main/java/KickIt/server/domain/teams/controller/SquadController.java
  src/main/java/KickIt/server/domain/teams/dto/SquadDto.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/domain/teams/entity/Squad.java
  src/main/java/KickIt/server/domain/teams/entity/SquadRepository.java
  src/main/java/KickIt/server/domain/teams/service/SquadService.java
  src/main/java/KickIt/server/global/common/crawler/SquadCrawler.java
Labels: 🌼 인영, 🎉 Feat

#46 Sf 85/feat/#44 naver login
  build.gradle
  src/main/java/KickIt/server/ServerApplication.java
  src/main/java/KickIt/server/domain/realtime/controller/RealTimeController.java
  src/main/java/KickIt/server/domain/realtime/dto/RealTimeRepository.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTime.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeService.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeStart.java
  src/main/java/KickIt/server/domain/user/AuthTokens.java
  src/main/java/KickIt/server/domain/user/AuthTokensGenerator.java
  src/main/java/KickIt/server/domain/user/ClientConfig.java
  src/main/java/KickIt/server/domain/user/JwtTokenProvider.java
  src/main/java/KickIt/server/domain/user/OAuthApiClient.java
  src/main/java/KickIt/server/domain/user/OAuthInfoResponse.java
  src/main/java/KickIt/server/domain/user/OAuthLoginParams.java
  src/main/java/KickIt/server/domain/user/OAuthLoginService.java
  src/main/java/KickIt/server/domain/user/OAuthProvider.java
  src/main/java/KickIt/server/domain/user/RequestOAuthInfoService.java
  src/main/java/KickIt/server/domain/user/controller/AuthController.java
  src/main/java/KickIt/server/domain/user/controller/MemberController.java
  src/main/java/KickIt/server/domain/user/dto/MemberDto.java
  src/main/java/KickIt/server/domain/user/dto/MemberRepository.java
  src/main/java/KickIt/server/domain/user/dto/NaverInfoResponse.java
  src/main/java/KickIt/server/domain/user/dto/NaverLoginParams.java
  src/main/java/KickIt/server/domain/user/dto/NaverTokens.java
  src/main/java/KickIt/server/domain/user/entity/Member.java
  src/main/java/KickIt/server/domain/user/service/MemberService.java
  src/main/java/KickIt/server/domain/user/service/NaverApiClient.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeCrawler.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeDataParser.java
  src/main/java/KickIt/server/global/util/DataSend.java
  src/main/resources/application.properties
  src/test/java/KickIt/Server/StatusTest.java
Labels: 🌷 윤수, ✅ Chore

#47 🔧 Fix: post API 호출 후 중복 저장하는 오류 선수 update만 하도록 수정
  src/main/java/KickIt/server/domain/teams/entity/Squad.java
  src/main/java/KickIt/server/domain/teams/service/SquadService.java
Labels: 🐞 Bug&Fix
