Repository Team-Safezone/Safezone-Server, pull requests merged in 2024-05, with the labels that each got.

#9 🎉 Feat: 프리미어리그 경기 일정 중 크롤링해 오는 정보 추가
  .gitignore
  .idea/.name
  .idea/Safezone-Server.iml
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/KickIt/server/domain/fixture/entity/Fixture.java
  src/main/java/KickIt/server/global/common/crawler/FixtureCrawler.java
Labels: 🌼 인영, 🎉 Feat, :page_facing_up: Data Crawling

#11 Merge pull request Sf 44/feat/#8 crawling rt crawler10
  build.gradle
  src/main/java/KickIt/server/domain/realtime/RealTime.java
  src/main/java/KickIt/server/global/common/crawler/RTCrawler.java
Labels: 🎉 Feat, 🌷 윤수, :page_facing_up: Data Crawling

#10 Sf 42/feat/#6 crawling lineup crawler
  src/main/java/KickIt/server/domain/lineup/entity/MatchLineup.java
  src/main/java/KickIt/server/domain/lineup/entity/TeamLineup.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/global/common/crawler/FixtureCrawler.java
  src/main/java/KickIt/server/global/common/crawler/LineupCrawler.java
  src/main/java/KickIt/server/global/common/crawler/test.java
  src/main/java/KickIt/server/global/util/WebDriverUtil.java
Labels: 🌼 인영, 🎉 Feat, :page_facing_up: Data Crawling

#17 🎉 Feat: 팀별 선수 명단 정보 크롤링하는 SquadCrawler 추가
  src/main/java/KickIt/server/domain/teams/EplTeams.java
  src/main/java/KickIt/server/domain/teams/PlayerPosition.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/domain/teams/entity/Squad.java
  src/main/java/KickIt/server/global/common/crawler/FixtureCrawler.java
  src/main/java/KickIt/server/global/common/crawler/SquadCrawler.java
  src/main/java/KickIt/server/global/common/crawler/test.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore, :page_facing_up: Data Crawling

#19 🎉feat: 기존 시즌 선수 명단에 공식 선수 프로필 이미지 주소 추가 크롤링
  src/main/java/KickIt/server/domain/teams/EplTeams.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/global/common/crawler/SquadCrawler.java
  src/main/java/KickIt/server/global/common/crawler/test.java
Labels: 🐞 Bug&Fix, 🌼 인영, 🎉 Feat, :page_facing_up: Data Crawling
