Repository Team-Safezone/Safezone-Server, pull requests merged in 2024-10, with the labels that each got.

#49 Sf 90/feat/#48 naver login refactoring
  src/main/java/KickIt/server/AppConfig.java
  src/main/java/KickIt/server/domain/member/JwtService.java
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/member/dto/MemberRepository.java
  src/main/java/KickIt/server/domain/member/entity/AuthProvider.java
  src/main/java/KickIt/server/domain/member/entity/LoginRequest.java
  src/main/java/KickIt/server/domain/member/entity/Member.java
  src/main/java/KickIt/server/domain/member/entity/SignupRequest.java
  src/main/java/KickIt/server/domain/member/service/MemberService.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTime.java
  src/main/java/KickIt/server/domain/user/AuthTokens.java
  src/main/java/KickIt/server/domain/user/AuthTokensGenerator.java
  src/main/java/KickIt/server/domain/user/JwtTokenProvider.java
  src/main/java/KickIt/server/domain/user/OAuthApiClient.java
  src/main/java/KickIt/server/domain/user/OAuthInfoResponse.java
  src/main/java/KickIt/server/domain/user/OAuthLoginParams.java
  src/main/java/KickIt/server/domain/user/OAuthLoginService.java
  src/main/java/KickIt/server/domain/user/OAuthProvider.java
  src/main/java/KickIt/server/domain/user/RequestOAuthInfoService.java
  src/main/java/KickIt/server/domain/user/controller/AuthController.java
  src/main/java/KickIt/server/domain/user/controller/MemberController.java
  src/main/java/KickIt/server/domain/user/dto/MemberDto.java
  src/main/java/KickIt/server/domain/user/dto/MemberRepository.java
  src/main/java/KickIt/server/domain/user/dto/NaverInfoResponse.java
  src/main/java/KickIt/server/domain/user/dto/NaverLoginParams.java
  src/main/java/KickIt/server/domain/user/dto/NaverTokens.java
  src/main/java/KickIt/server/domain/user/entity/Member.java
  src/main/java/KickIt/server/domain/user/service/MemberService.java
  src/main/java/KickIt/server/domain/user/service/NaverApiClient.java
  src/main/java/KickIt/server/global/util/DataSend.java
  src/main/resources/application.properties
Labels: 🎉 Feat, 🌷 윤수

#50 Sf 82/feat/#41 team and match line up api
  src/main/java/KickIt/server/domain/lineup/controller/MatchLineupController.java
  src/main/java/KickIt/server/domain/lineup/dto/MatchLineupDto.java
  src/main/java/KickIt/server/domain/lineup/entity/MatchLineup.java
  src/main/java/KickIt/server/domain/lineup/entity/MatchLineupRepository.java
  src/main/java/KickIt/server/domain/lineup/entity/TeamLineup.java
  src/main/java/KickIt/server/domain/lineup/service/MatchLineupService.java
  src/main/java/KickIt/server/domain/teams/entity/Player.java
  src/main/java/KickIt/server/domain/teams/entity/PlayerRepository.java
  src/main/java/KickIt/server/domain/teams/entity/SquadRepository.java
  src/main/java/KickIt/server/global/common/crawler/LineupCrawler.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore

#60 🎉 Feat: jwt package
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeStart.java
  src/main/java/KickIt/server/global/util/DataSend.java
  src/main/java/KickIt/server/jwt/JwtService.java
  src/main/java/KickIt/server/jwt/jwtTokenUtil.java
Labels: 🎉 Feat, 🌷 윤수

#61 🎉 Feat: API 명세서 변경에 따른 시즌 정보 / 시즌 내 팀 정보 필드 추가
  src/main/java/KickIt/server/domain/fixture/controller/FixtureController.java
  src/main/java/KickIt/server/domain/fixture/dto/FixtureDto.java
  src/main/java/KickIt/server/domain/fixture/service/FixtureService.java
  src/main/java/KickIt/server/domain/teams/entity/SquadRepository.java
  src/main/java/KickIt/server/domain/teams/service/SquadService.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore

#66 ✅ Chore: 네이버에서 카카오로 로직 변경
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/member/entity/AuthProvider.java
  src/main/java/KickIt/server/domain/member/entity/Member.java
  src/main/java/KickIt/server/domain/member/service/MemberService.java
Labels: 🌷 윤수, ✅ Chore
