Repository Team-Safezone/Safezone-Server, pull requests merged in 2024-11, with the labels that each got.

#67 Sf 114/feat/#65 mypage
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/member/dto/FavoriteTeamsDto.java
  src/main/java/KickIt/server/domain/member/dto/MemberRepository.java
  src/main/java/KickIt/server/domain/member/dto/MypageDto.java
  src/main/java/KickIt/server/domain/member/dto/NicknameDto.java
  src/main/java/KickIt/server/domain/member/entity/Member.java
  src/main/java/KickIt/server/domain/member/entity/MemberRepository.java
  src/main/java/KickIt/server/domain/member/service/MemberService.java
  src/main/java/KickIt/server/domain/teams/entity/SquadRepository.java
  src/main/java/KickIt/server/jwt/JwtTokenUtil.java
Labels: 🎉 Feat, 🌷 윤수

#75 🎉 Feat: 우승팀 예측 POST API 개발
  src/main/java/KickIt/server/domain/lineupPrediction/controller/LineupPredictionController.java
  src/main/java/KickIt/server/domain/lineupPrediction/dto/LineupPredictionDto.java
  src/main/java/KickIt/server/domain/lineupPrediction/entity/LineupPrediction.java
  src/main/java/KickIt/server/domain/lineupPrediction/entity/LineupPredictionId.java
  src/main/java/KickIt/server/domain/lineupPrediction/entity/LineupPredictionRepository.java
  src/main/java/KickIt/server/domain/lineupPrediction/entity/PredictionPlayer.java
  src/main/java/KickIt/server/domain/lineupPrediction/service/LineupPredictionService.java
  src/main/java/KickIt/server/domain/scorePrediction/controller/ScorePredictionController.java
  src/main/java/KickIt/server/domain/scorePrediction/dto/ScorePredictionDto.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePrediction.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePredictionRepository.java
  src/main/java/KickIt/server/domain/scorePrediction/service/ScorePredictionService.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore

#76 🎉 Feat: 우승팀 예측 수정 PATCH API 개발
  src/main/java/KickIt/server/domain/scorePrediction/controller/ScorePredictionController.java
  src/main/java/KickIt/server/domain/scorePrediction/dto/ScorePredictionDto.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePrediction.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePredictionRepository.java
  src/main/java/KickIt/server/domain/scorePrediction/service/ScorePredictionService.java
Labels: 🌼 인영, 🎉 Feat

#79 Sf 89/feat/#55 save heart rate
  src/main/java/KickIt/server/ServerApplication.java
  src/main/java/KickIt/server/domain/fixture/entity/FixtureRepository.java
  src/main/java/KickIt/server/domain/fixture/service/FixtureService.java
  src/main/java/KickIt/server/domain/heartRate/controller/HeartRateController.java
  src/main/java/KickIt/server/domain/heartRate/dto/HeartRateDto.java
  src/main/java/KickIt/server/domain/heartRate/dto/MinAvgMaxDto.java
  src/main/java/KickIt/server/domain/heartRate/dto/RealTimeStatisticsDto.java
  src/main/java/KickIt/server/domain/heartRate/dto/StatisticsDto.java
  src/main/java/KickIt/server/domain/heartRate/entity/FixtureHeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/FixtureHeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRate.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/StatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRate.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/service/FixtureHeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateParser.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateService.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/heartRate/service/StatisticsService.java
  src/main/java/KickIt/server/domain/heartRate/service/TeamHeartRateService.java
  src/main/java/KickIt/server/domain/heartRate/service/TeamHeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/lineupPrediction/controller/LineupPredictionController.java
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/member/entity/Member.java
  src/main/java/KickIt/server/domain/member/entity/MemberRepository.java
  src/main/java/KickIt/server/domain/member/service/MemberService.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTimeRepository.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeService.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeStart.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeCrawler.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeDataParser.java
  src/main/java/KickIt/server/jwt/JwtService.java
Labels: 🎉 Feat, 🌷 윤수, ✅ Chore

#80 🎉 Feat: 우승팀 예측 조회 GET API 개발
  src/main/java/KickIt/server/domain/scorePrediction/controller/ScorePredictionController.java
  src/main/java/KickIt/server/domain/scorePrediction/dto/ScorePredictionDto.java
  src/main/java/KickIt/server/domain/scorePrediction/service/ScorePredictionService.java
Labels: 🌼 인영, 🎉 Feat

#90 🎉 Feat: 경기 예측 조회 GET API
  src/main/java/KickIt/server/domain/lineupPrediction/entity/LineupPredictionRepository.java
  src/main/java/KickIt/server/domain/lineupPrediction/service/LineupPredictionService.java
  src/main/java/KickIt/server/domain/matchPrediction/controller/MatchPredictionController.java
  src/main/java/KickIt/server/domain/matchPrediction/dto/MatchPredictionDto.java
  src/main/java/KickIt/server/domain/matchPrediction/service/MatchPredictionService.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePredictionRepository.java
  src/main/java/KickIt/server/domain/scorePrediction/service/ScorePredictionService.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore

#95 ✅ Chore: API 수정
  src/main/java/KickIt/server/domain/member/controller/MemberController.java
  src/main/java/KickIt/server/domain/realtime/controller/RealTimeController.java
Labels: 🐞 Bug&Fix, 🌷 윤수, ✅ Chore

#96 🎉 Feat: 최근 시즌 팀 이름, URL 조회 API 개발
  src/main/java/KickIt/server/domain/teams/controller/SquadController.java
  src/main/java/KickIt/server/domain/teams/dto/SquadDto.java
  src/main/java/KickIt/server/domain/teams/entity/SquadRepository.java
  src/main/java/KickIt/server/domain/teams/service/SquadService.java
Labels: 🌼 인영, 🎉 Feat

#98 Sf 139/fix/#97 real timetime heart rate
  src/main/java/KickIt/server/domain/diary/entity/Diary.java
  src/main/java/KickIt/server/domain/diary/entity/DiaryLiked.java
  src/main/java/KickIt/server/domain/diary/entity/DiaryPhoto.java
  src/main/java/KickIt/server/domain/diary/entity/DiaryReport.java
  src/main/java/KickIt/server/domain/fixture/entity/Fixture.java
  src/main/java/KickIt/server/domain/fixture/entity/FixtureRepository.java
  src/main/java/KickIt/server/domain/fixture/service/FixtureService.java
  src/main/java/KickIt/server/domain/heartRate/controller/HeartRateController.java
  src/main/java/KickIt/server/domain/heartRate/dto/EventHeartRateDto.java
  src/main/java/KickIt/server/domain/heartRate/entity/FixtureHeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/FixtureHeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRate.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/HeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/StatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRate.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateRepository.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateStatistics.java
  src/main/java/KickIt/server/domain/heartRate/entity/TeamHeartRateStatisticsRepository.java
  src/main/java/KickIt/server/domain/heartRate/service/FixtureHeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateParser.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateService.java
  src/main/java/KickIt/server/domain/heartRate/service/HeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/heartRate/service/TeamHeartRateService.java
  src/main/java/KickIt/server/domain/heartRate/service/TeamHeartRateStatisticsService.java
  src/main/java/KickIt/server/domain/member/entity/Member.java
  src/main/java/KickIt/server/domain/realtime/controller/RealTimeController.java
  src/main/java/KickIt/server/domain/realtime/dto/RealTimeDto.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTime.java
  src/main/java/KickIt/server/domain/realtime/entity/RealTimeRepository.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeService.java
  src/main/java/KickIt/server/domain/realtime/service/RealTimeStart.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeCrawler.java
  src/main/java/KickIt/server/global/common/crawler/RealTimeDataParser.java
  src/main/java/KickIt/server/global/util/CreatedAt.java
Labels: 🐞 Bug&Fix, 🌷 윤수, ✅ Chore

#101 기록하고 싶은 경기 선택을 위한 경기 일정 조회 GET API 개발 완료
  src/main/java/KickIt/server/domain/fixture/controller/FixtureController.java
  src/main/java/KickIt/server/domain/fixture/dto/FixtureDto.java
  src/main/java/KickIt/server/domain/fixture/service/FixtureService.java
  src/main/java/KickIt/server/domain/teams/service/SquadService.java
Labels: 🐞 Bug&Fix, 🎉 Feat, ✅ Chore

#105 Sf 134/feat/#92 diary recommend
  .gitignore
  src/main/java/KickIt/server/domain/diary/controller/DiaryController.java
  src/main/java/KickIt/server/domain/diary/dto/DiaryIdRequest.java
  src/main/java/KickIt/server/domain/diary/dto/DiaryLikeDto.java
  src/main/java/KickIt/server/domain/diary/dto/DiaryRecommendDto.java
  src/main/java/KickIt/server/domain/diary/dto/DiarySaveDto.java
  src/main/java/KickIt/server/domain/diary/entity/DiaryRepository.java
  src/main/java/KickIt/server/domain/diary/service/DiaryDataParser.java
  src/main/java/KickIt/server/domain/diary/service/DiaryRecommendService.java
  src/main/java/KickIt/server/domain/diary/service/DiaryService.java
  src/main/java/KickIt/server/domain/diary/service/MyDiaryService.java
  src/main/java/KickIt/server/domain/member/entity/MemberRepository.java
Labels: 🎉 Feat, 🌷 윤수, ✅ Chore

#106 Sf 143/feat/#103 home api
  src/main/java/KickIt/server/domain/fixture/entity/FixtureRepository.java
  src/main/java/KickIt/server/domain/home/controller/HomeController.java
  src/main/java/KickIt/server/domain/home/dto/HomeDto.java
  src/main/java/KickIt/server/domain/home/service/HomeService.java
  src/main/java/KickIt/server/domain/lineupPrediction/dto/LineupPredictionDto.java
  src/main/java/KickIt/server/domain/matchPrediction/dto/MatchPredictionDto.java
  src/main/java/KickIt/server/domain/matchPrediction/service/MatchPredictionService.java
  src/main/java/KickIt/server/domain/scorePrediction/dto/ScorePredictionDto.java
  src/main/java/KickIt/server/domain/scorePrediction/entity/ScorePredictionRepository.java
  src/main/java/KickIt/server/domain/teams/service/RankingService.java
Labels: 🌼 인영, 🎉 Feat, ✅ Chore
